// import { n, s, b, a } from './../values'
// export const contractServiceCheck = {
//   id: n,
//   contractId: n,
//   serviceId: n,
//   userGroupId: n,
//   sum: n,
//   accountSum: n,
//   dateFrom: s,
//   dateTo: s,
//   status: n,
//   service: {
//     id: n,
//     name: s,
//     description: s,
//     directionId: n,
//     cbcId: n,
//     serviceType: n,
//     templateId: n,
//     countHours: [0, n],
//     comment: s,
//     removed: n | b,
//     groupCount: [0, n],
//     isNavigator: n,
//   },
//   userGroup: {
//     id: n,
//     dateFrom: s,
//     dateTo: s,
//     user: {
//       id: s,
//       login: s,
//       paymentKey: s,
//       userDetails: [
//         {
//           id: [0, n],
//           userId: s,
//           firstName: s,
//           middleName: s,
//           lastName: s,
//           birthday: [0, s],
//         }
//       ]
//     },
//     group: {
//       id: n,
//       name: s,
//       description: s,
//       serviceId: n,
//       teacherId: n,
//       placeId: [0, n],
//       status: n,
//       startTime: s,
//       endTime: s,
//       personCount: n,
//       userCount: [0, n],
//       serviceModules: a,
//     },
//   },
// }

// export const contractGetApiResponseItemCheck = {
//   "id": n,
//   items: [n],
//   "userId": n,
//   "number": [0, s, n],
//   "content": a,
//   "sum": n,
//   "status": n,
//   "dateFrom": s,
//   "dateTo": s,
//   "phone": s,
//   "parentLastName": a,
//   "parentFirstName": 0,
//   "parentMiddleName": 0,
//   "documentType": 0,
//   "documentSerie": 0,
//   "documentNumber": 0,
//   "documentIssuer": 0,
//   "documentIssueDate": 0,
//   "documentDivisionCode": 0,
//   "contractServices": [contractServiceCheck],
//   "templateUrl": a
// }

